# Generated by Django 4.2.4 on 2023-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
